name: sync-with-playwright

volumes:
  supabase_storage:
  supabase_db:

networks:
  default:
    name: sync-with-playwright_default
  supabase:
    name: sync-with-playwright_supabase

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    ports:
      - 127.0.0.1:5433:5432
    

